# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  LoggingApp_config = debug
endif
ifeq ($(config),release)
  LoggingApp_config = release
endif

PROJECTS := LoggingApp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

LoggingApp:
ifneq (,$(LoggingApp_config))
	@echo "==== Building LoggingApp ($(LoggingApp_config)) ===="
	@${MAKE} --no-print-directory -C . -f LoggingApp.make config=$(LoggingApp_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f LoggingApp.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   LoggingApp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"