# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  LoggingCpp_config = debug
endif
ifeq ($(config),release)
  LoggingCpp_config = release
endif

PROJECTS := LoggingCpp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

LoggingCpp:
ifneq (,$(LoggingCpp_config))
	@echo "==== Building LoggingCpp ($(LoggingCpp_config)) ===="
	@${MAKE} --no-print-directory -C . -f LoggingCpp.make config=$(LoggingCpp_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f LoggingCpp.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   LoggingCpp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"